version: "3.9"

services:

  # ----------------------
  # PostgreSQL
  postgres:
    image: postgres:15
    container_name: shop-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - shop-net

  # ----------------------
  # Zookeeper (Kafka dependency)
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: shop-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - shop-net

  # ----------------------
  # Kafka
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: shop-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      # listeners
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - shop-net

  # ----------------------
  # order-service:
  #   build: ./order-service
  #   container_name: order-service
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - postgres
  #     - kafka
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
  #     SPRING_DATASOURCE_USERNAME: postgres
  #     SPRING_DATASOURCE_PASSWORD: postgres
  #     SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  #   networks:
  #     - shop-net

  # ----------------------
  # notification-service:
  #   build: ./notification-service
  #   container_name: notification-service
  #   ports:
  #     - "8082:8082"
  #   depends_on:
  #     - postgres
  #     - kafka
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
  #     SPRING_DATASOURCE_USERNAME: postgres
  #     SPRING_DATASOURCE_PASSWORD: postgres
  #     SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  #   networks:
  #     - shop-net

networks:
  shop-net:

volumes:
  pgdata:
